export type SourceCatalogItem = {
  name: string; baseUrl: string; sourceFamily: string; geographicLevel: string; territoryLabel: string;
  isOfficial: boolean; priority: number; collectionMethod: "manual" | "api" | "rss" | "scrape" | "email" | "import" | "unknown"; notes: string;
};

export const PRIORITY_BUSINESS_SOURCES: SourceCatalogItem[] = [
  { name: "Investissement Québec", baseUrl: "https://www.investquebec.com/fr/financement/programmes-gouvernementaux", sourceFamily: "crown_corporation", geographicLevel: "province_territory", territoryLabel: "Québec", isOfficial: true, priority: 1, collectionMethod: "scrape", notes: "Source officielle prioritaire pour les programmes administrés par Investissement Québec." },
  { name: "Québec.ca — Liste des aides financières", baseUrl: "https://www.quebec.ca/entreprises-et-travailleurs-autonomes/liste-partielle-aide-financiere", sourceFamily: "official_provincial_portal", geographicLevel: "province_territory", territoryLabel: "Québec", isOfficial: true, priority: 1, collectionMethod: "scrape", notes: "Portail gouvernemental général; Apex masque par défaut les programmes non pertinents pour entreprises." },
  { name: "Services Québec — Formation de la main-d’œuvre (MFOR)", baseUrl: "https://www.quebec.ca/entreprises-et-travailleurs-autonomes/administrer-gerer/embauche-gestion-personnel/former-main-oeuvre/developper-competences", sourceFamily: "provincial_ministry", geographicLevel: "province_territory", territoryLabel: "Québec", isOfficial: true, priority: 1, collectionMethod: "scrape", notes: "Formation et développement des compétences des travailleurs." },
  { name: "Services Québec — Subvention salariale", baseUrl: "https://www.quebec.ca/entreprises-et-travailleurs-autonomes/administrer-gerer/embauche-gestion-personnel/recruter/aider-personne-integrer-emploi-maniere-durable", sourceFamily: "provincial_ministry", geographicLevel: "province_territory", territoryLabel: "Québec", isOfficial: true, priority: 1, collectionMethod: "scrape", notes: "Aide à l’embauche d’une personne pour intégrer un emploi durable." },
  { name: "Innovation Canada — Business Benefits Finder", baseUrl: "https://innovation.ised-isde.canada.ca/s/?language=fr_CA", sourceFamily: "official_federal_aggregator", geographicLevel: "canada", territoryLabel: "Canada", isOfficial: true, priority: 1, collectionMethod: "unknown", notes: "Agrégateur officiel pancanadien." },
  { name: "TECHNATION — Career Ready", baseUrl: "https://careerready.technationcanada.ca/", sourceFamily: "funding_intermediary", geographicLevel: "canada", territoryLabel: "Canada", isOfficial: false, priority: 1, collectionMethod: "scrape", notes: "Subvention salariale SWPP pour stages technologiques." },
  { name: "ICTC — WIL Digital", baseUrl: "https://ictc-ctic.smapply.ca/prog/wil_digital/", sourceFamily: "funding_intermediary", geographicLevel: "canada", territoryLabel: "Canada", isOfficial: false, priority: 1, collectionMethod: "scrape", notes: "Subvention salariale pour stages étudiants en économie numérique." },
  { name: "ECO Canada — Stages pratiques pour étudiants", baseUrl: "https://eco.ca/fr/etudiants/programme-de-stages-pour-etudiants/", sourceFamily: "funding_intermediary", geographicLevel: "canada", territoryLabel: "Canada", isOfficial: false, priority: 1, collectionMethod: "scrape", notes: "Stages étudiants en environnement, STEAM et affaires." },
  { name: "Pratiques RH — Accueillez un stagiaire", baseUrl: "https://pratiquesrh.com/services/accueillez-un-stagiaire", sourceFamily: "funding_intermediary", geographicLevel: "province_territory", territoryLabel: "Québec", isOfficial: false, priority: 1, collectionMethod: "scrape", notes: "Programme de stages au Québec avec périodes de dépôt et liste de pièces à préparer." },
  { name: "helloDarwin — Subventions et financement", baseUrl: "https://hellodarwin.com/fr/aide-aux-entreprises/subventions-et-financement", sourceFamily: "private_aggregator", geographicLevel: "canada", territoryLabel: "Canada", isOfficial: false, priority: 2, collectionMethod: "unknown", notes: "Source secondaire de découverte; validation sur la source officielle." },
  { name: "Fundica", baseUrl: "https://visa.fundica.ca/home/fr", sourceFamily: "private_aggregator", geographicLevel: "canada", territoryLabel: "Canada", isOfficial: false, priority: 2, collectionMethod: "unknown", notes: "Moteur de financement orienté entreprises." },
];
